FROM nginx AS build
WORKDIR /src
RUN apt-get update && \
    apt-get install -y git gcc make g++ perl libunwind-dev && \
    git clone -b openssl-3.0.8-quic1 --depth=1 https://github.com/quictls/openssl.git 
    
RUN apt-get install -y mercurial libperl-dev libpcre3-dev zlib1g-dev libxslt1-dev libgd-ocaml-dev libgeoip-dev && \
    hg clone https://hg.nginx.org/nginx-quic && \
    hg clone http://hg.nginx.org/njs && \
    cd nginx-quic && \
    hg update quic && \
    ./auto/configure --with-debug \
        --prefix=/home/nginx \
        --with-http_v2_module \
        --with-http_v3_module \
        --with-stream_quic_module \
        --with-openssl="/src/openssl" && \
    make && make install

FROM debian:bullseye-slim

RUN mkdir /home/nginx && apt-get update && apt-get install -y libpcre3 libpcre3-dev

COPY --from=build /home/nginx /home/nginx

# ENV LD_LIBRARY_PATH /usr/local/lib
ENV PATH /home/nginx/sbin:$PATH

WORKDIR /home/nginx/sbin

ENTRYPOINT ["nginx","-g","daemon off;"]